apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: permission-post-access-webfilter
spec:
  className: com.haoshenqi.permission.PostAccessWebFilter
  extensionPointName: after-security-webfilter
  displayName: "Post access permission web filter"
  description: "Restrict theme-side post access by post metadata annotations."
